### ISSUE TITLE
reusing and extxyz file wrote by janus crashes the workflow

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#290]
do a geom opt of any system and save it as extxyz, or default

try to use it for example in another geom opt but with stricter params... 

you will get a stress not found or force not found...

**Comment by ElliottKasoar** [comment]
What do you mean stricter params? Could you share an example of the two `geomopt` commands?

**Comment by alinelena** [comment]
janus geomopt --config configs/geom-all.yml --struct data/NaCl-deformed.cif 
janus geomopt --config configs/geom-all.yml --struct NaCl-opt.extxyz --fmax 0.0001

ase.calculators.calculator.PropertyNotImplementedError: The property "stress" is not available.

the data is from our tutorials... which also need to be updated to the latest syntax changes.

**Comment by ElliottKasoar** [comment]
Ah I see, thanks. That's a more general issue that the default for `set_calc` isn't being set properly when we read in files, so the PR should fix that.

The tutorials should all be updated (consistent with the the most recent release on PyPI, so need updating again soon), and there's a draft PR for the full config files for each command too.

**Comment by alinelena** [comment]
calculating descriptors on a results file throws errors...

  File "/work4/scd/scarf562/micromamba/micromamba/envs/janus/lib/python3.12/site-packages/janus_core/calculations/descriptors.py", line 206, in _calc_descriptors
    arch = struct.calc.parameters["arch"]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^

KeyError: 'arch'

**Comment by ElliottKasoar** [comment]
I think that my incidentally be fixed by #295

**Comment by alinelena** [comment]
ok there is a simple comment on that but other I am ok with it

**Comment by alinelena** [comment]
to test add something like magmom=0.00062 in the info and then

try to compute the descriptors on such a structure from cli.

**Comment by ElliottKasoar** [comment]
Are you sure that's not the issue that was fixed yesterday by #291?

With a file like 

```
8
Lattice="5.64 0.0 0.0 0.0 5.64 0.0 0.0 0.0 5.64" Properties=species:S:1:pos:R:3 magmom=0.00062 pbc="T T T"
```

It would have broken before that was merged, but now works without the need for extra checks (though I've added them anyway)

**Comment by alinelena** [comment]
the issue is indeed the same but somehow seems was not fixed

**Comment by ElliottKasoar** [comment]
Are you able to share a file and command combination that doesn't work? I haven't managed to reproduce this

**Comment by ElliottKasoar** [comment]
It is definitely unique to structures with extra info?

I'm wondering if it's due to adding dispersion, which may lead to similar errors as the `SinglePointCalculator` errors that are (should be) fixed, as it sets up a `SumCalculator`, which I don't think we handle sufficiently (e.g. we get errors with `get_descriptors` too).

**Comment by alinelena** [comment]
is this not fixed?

**Comment by ElliottKasoar** [comment]
I'm not completely sure, since I don't think I managed to reproduce exactly the error you seemed to have, once #291 was merged.

There are still generally potential issues around `SumCalculator`s that aren't necessarily as fixed as I'd like (see #309), but I don't know if that was the issue.

I can't find any problems though e.g.

```
janus geomopt --struct tests/data/NaCl-deformed.cif--calc-kwargs "{'dispersion': True}"
janus geomopt --struct NaCl-deformed-opt.extxyz --calc-kwargs "{'dispersion': True}" --fmax 0.001
```
works for me, even inserting an extra `magmom=0.00062` in `NaCl-deformed-opt.extxyz` info, so I'll assume it's fixed until I get a concrete example otherwise.
